package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"log"
	"os"
	"path"
	"path/filepath"
	"sort"

	"golang.org/x/tools/go/packages"
)

const (
	modulePath              = "github.com/Space-DF/transformer-service"
	deviceProfilesImportDir = modulePath + "/internal/device_profiles"
	outputFile              = "internal/device_profiles/registry_gen.go"
)

type registrar struct {
	alias      string
	importPath string
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		return err
	}

	registrars, err := findRegistrars(moduleRoot)
	if err != nil {
		return err
	}

	return writeGeneratedFile(filepath.Join(moduleRoot, outputFile), registrars)
}

func findRegistrars(moduleRoot string) ([]registrar, error) {
	cfg := &packages.Config{
		Dir:   moduleRoot,
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedSyntax,
		Tests: false,
	}

	pkgs, err := packages.Load(cfg, deviceProfilesImportDir+"/...")
	if err != nil {
		return nil, err
	}

	var registrars []registrar
	for _, pkg := range pkgs {
		for _, pkgErr := range pkg.Errors {
			return nil, pkgErr
		}
		if shouldSkipPackage(pkg) {
			continue
		}

		register, ok := findRegisterFunc(pkg)
		if !ok {
			return nil, fmt.Errorf("%s: missing Register(common.ParserRegistry) error", pkg.PkgPath)
		}
		if !hasRegisterSignature(register) {
			return nil, fmt.Errorf("%s: Register must have signature func Register(common.ParserRegistry) error", pkg.PkgPath)
		}

		registrars = append(registrars, registrar{
			alias:      pkg.Name,
			importPath: pkg.PkgPath,
		})
	}

	sort.Slice(registrars, func(i, j int) bool {
		return registrars[i].importPath < registrars[j].importPath
	})
	if len(registrars) == 0 {
		return nil, fmt.Errorf("no device profile registrars found under %s", deviceProfilesImportDir)
	}
	return registrars, nil
}

func shouldSkipPackage(pkg *packages.Package) bool {
	switch pkg.PkgPath {
	case deviceProfilesImportDir,
		deviceProfilesImportDir + "/common",
		deviceProfilesImportDir + "/genregistrars":
		return true
	default:
		return pkg.Name == "main"
	}
}

func findRegisterFunc(pkg *packages.Package) (*ast.FuncDecl, bool) {
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if ok && fn.Recv == nil && fn.Name.Name == "Register" {
				return fn, true
			}
		}
	}
	return nil, false
}

func hasRegisterSignature(fn *ast.FuncDecl) bool {
	params := fn.Type.Params
	results := fn.Type.Results
	if params == nil || results == nil || len(params.List) != 1 || len(results.List) != 1 {
		return false
	}

	param, ok := params.List[0].Type.(*ast.SelectorExpr)
	if !ok || param.Sel.Name != "ParserRegistry" {
		return false
	}
	pkgName, ok := param.X.(*ast.Ident)
	if !ok || pkgName.Name != "common" {
		return false
	}

	result, ok := results.List[0].Type.(*ast.Ident)
	return ok && result.Name == "error"
}

func writeGeneratedFile(outputPath string, registrars []registrar) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("package deviceprofile\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/Space-DF/transformer-service/internal/device_profiles/common\"\n")
	for _, registrar := range registrars {
		if registrar.alias == pathBase(registrar.importPath) {
			fmt.Fprintf(&buf, "\t%q\n", registrar.importPath)
			continue
		}
		fmt.Fprintf(&buf, "\t%s %q\n", registrar.alias, registrar.importPath)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("var generatedRegistrars = []func(common.ParserRegistry) error{\n")
	for _, registrar := range registrars {
		fmt.Fprintf(&buf, "\t%s.Register,\n", registrar.alias)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(outputPath, formatted, 0o600)
}

func findModuleRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}

		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("go.mod not found")
		}
		wd = parent
	}
}

func pathBase(importPath string) string {
	return path.Base(importPath)
}
