// Code generated by go generate; DO NOT EDIT.

package deviceprofile

import (
	"github.com/Space-DF/transformer-service/internal/device_profiles/abeeway/industrial_tracker"
	"github.com/Space-DF/transformer-service/internal/device_profiles/common"
	"github.com/Space-DF/transformer-service/internal/device_profiles/digital_matter/g62"
	"github.com/Space-DF/transformer-service/internal/device_profiles/digital_matter/yabby_edge"
	"github.com/Space-DF/transformer-service/internal/device_profiles/dragino/lcc01lb"
	"github.com/Space-DF/transformer-service/internal/device_profiles/dragino/lsn50v2_s31"
	"github.com/Space-DF/transformer-service/internal/device_profiles/dut/wlbv1"
	"github.com/Space-DF/transformer-service/internal/device_profiles/lilygo/tbeam"
	"github.com/Space-DF/transformer-service/internal/device_profiles/mclimate/ht"
	"github.com/Space-DF/transformer-service/internal/device_profiles/milesight/am307"
	"github.com/Space-DF/transformer-service/internal/device_profiles/milesight/ct101"
	"github.com/Space-DF/transformer-service/internal/device_profiles/netvox/r718n17"
	"github.com/Space-DF/transformer-service/internal/device_profiles/netvox/r809ag"
	"github.com/Space-DF/transformer-service/internal/device_profiles/quandify/cubicmeter"
	"github.com/Space-DF/transformer-service/internal/device_profiles/rakwireless/rak2270"
	"github.com/Space-DF/transformer-service/internal/device_profiles/rakwireless/rak4630"
	"github.com/Space-DF/transformer-service/internal/device_profiles/rakwireless/rak7200"
	"github.com/Space-DF/transformer-service/internal/device_profiles/seeed/sensecap_t1000"
	"github.com/Space-DF/transformer-service/internal/device_profiles/seeed/sensecap_t1000e"
)

var generatedRegistrars = []func(common.ParserRegistry) error{
	industrial_tracker.Register,
	g62.Register,
	yabby_edge.Register,
	lcc01lb.Register,
	lsn50v2_s31.Register,
	wlbv1.Register,
	tbeam.Register,
	ht.Register,
	am307.Register,
	ct101.Register,
	r718n17.Register,
	r809ag.Register,
	cubicmeter.Register,
	rak2270.Register,
	rak4630.Register,
	rak7200.Register,
	sensecap_t1000.Register,
	sensecap_t1000e.Register,
}
