manufacturers:
  - id: 735c87f8-b9c5-4637-b75e-0327626fb1c1
    name: RAKwireless
    description: RAKwireless Technology Limited
    portal_url: 
    
  - id: 957e6842-c686-40ae-8b28-bf3ddb1ad141
    name: DUT
    description: DUT Technology
    portal_url: 
